apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: troubleshooting-panel
    app.kubernetes.io/managed-by: observability-operator
    app.kubernetes.io/part-of: UIPlugin
  name: troubleshooting-panel-replace
  namespace: openshift-cluster-observability-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: troubleshooting-panel
      app.kubernetes.io/managed-by: observability-operator
      app.kubernetes.io/part-of: UIPlugin
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: troubleshooting-panel
        app.kubernetes.io/managed-by: observability-operator
        app.kubernetes.io/part-of: UIPlugin
      name: troubleshooting-panel
      namespace: openshift-cluster-observability-operator
    spec:
      containers:
      - args:
        - -port=9443
        - -cert=/var/serving-cert/tls.crt
        - -key=/var/serving-cert/tls.key
        - -plugin-config-path=/etc/plugin/config/config.yaml
        image: quay.io/alanconway/troubleshooting-panel-console-plugin:latest
        imagePullPolicy: Always
        name: troubleshooting-panel
        ports:
        - containerPort: 9443
          name: web
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /var/serving-cert
          name: serving-cert
          readOnly: true
        - mountPath: /etc/plugin/config
          name: plugin-config
          readOnly: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: troubleshooting-panel-sa
      serviceAccountName: troubleshooting-panel-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - name: serving-cert
        secret:
          defaultMode: 420
          secretName: troubleshooting-panel
      - configMap:
          defaultMode: 420
          name: troubleshooting-panel
        name: plugin-config
