apiVersion: v1
kind: Pod
metadata:
  name: traceql-search
spec:
  containers:
  - name: traceql-search
    image: ghcr.io/grafana/tempo-operator/test-utils:main
    command:
      - /bin/bash
      - -eux
      - -c
    args:
      - |
        curl -G \
          --header "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
          --cacert /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt \
          --data-urlencode 'q={ resource.service.name="article-service" }' \
          https://tempo-platform-gateway.openshift-tracing.svc.cluster.local:8080/api/traces/v1/platform/tempo/api/search | jq
  restartPolicy: Never

