apiVersion: v1
kind: Secret
metadata:
  name: seaweedfs
  namespace: netobserv
stringData:
  access_key_id: seaweedfs
  access_key_secret: seaweedfs123
  bucketnames: loki
  endpoint: http://seaweedfs.seaweedfs.svc:8333
type: Opaque
---
apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: loki
  namespace: netobserv
spec:
  size: 1x.demo
  storage:
    schemas:
    - effectiveDate: '2022-06-01'
      version: v13
    secret:
      name: seaweedfs
      type: s3
  storageClassName: local-storage
  tenants:
    mode: openshift-network
