apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: netobserv
stringData:
  access_key_id: minio
  access_key_secret: minio123
  bucketnames: loki
  endpoint: http://minio.minio.svc:9000
type: Opaque
---
apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: loki
  namespace: netobserv
spec:
  size: 1x.demo
  storage:
    schemas:
    - effectiveDate: '2022-06-01'
      version: v13
    secret:
      name: minio
      type: s3
  storageClassName: crc-csi-hostpath-provisioner
  tenants:
    mode: openshift-network
