apiVersion: ols.openshift.io/v1alpha1
kind: OLSConfig
metadata:
  name: cluster
spec:
  featureGates:
    - MCPServer
    - ToolFiltering
  llm:
    providers:
      - credentialKey: apitoken
        credentialsSecretRef:
          name: credentials-gcp-google
        googleVertexConfig:
          location: global
          projectID: itpc-gcp-hcm-pe-eng-claude
        models:
          - name: gemini-2.5-flash
          - name: gemini-3.5-flash
          - name: gemini-2.5-pro
        name: google
        type: google_vertex
      - credentialKey: apitoken
        credentialsSecretRef:
          name: credentials-gcp-anthropic
        googleVertexAnthropicConfig:
          location: us-east5
          projectID: itpc-gcp-hcm-pe-eng-claude
        models:
          - name: claude-opus-4-6
          - name: claude-opus-4-8
        name: anthropic
        type: google_vertex_anthropic
  ols:
    # NOTE needed for korrel8r - review.
    additionalCAConfigMapRef:
      name: service-ca-bundle
    defaultModel: claude-opus-4-6
    defaultProvider: anthropic
    toolsApprovalConfig:
      approvalType: never
  mcpServers:
    - name: korrel8r
      url: https://korrel8r.openshift-cluster-observability-operator.svc.cluster.local:9443/mcp
      timeout: 10
      headers:
        - name: Authorization
          valueFrom:
            type: kubernetes # Use the bearer-token for MCP servers
